p8105_hw1_ht2611.Rmd
================
ht2611
2022-09-20

P1

``` r
data("penguins", package = "palmerpenguins")
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

``` r
library(ggplot2)
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm,color=species)) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_ht2611_files/figure-gfm/unnamed-chunk-1-1.png)<!-- -->

``` r
ggsave("scatter_plot.pdf", height = 4, width = 6)
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

The variables are species, island, bill_length_mm, bill_depth_mm
flipper_length_mm, body_mass_g, sex, year. The nrow is 344, the ncol is
8, the mean flipper length is 200.9.

P2

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ✔ purrr   0.3.4      
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
example_df = tibble(
  rs=rnorm(10),
  vec_logical = (rs>1),
  vec_char = c("a", "b", "c", "d", "e", "f", "g", "h", "m", "n"),
  vec_factor = factor(c("level1", "level2", "level2", "level2", "level2", "level2", "level2", "level2", "level2", "level3"))
)
mean(example_df$rs)
```

    ## [1] 0.03864491

``` r
mean(example_df$vec_logical)
```

    ## [1] 0.1

``` r
mean(example_df$vec_char)
```

    ## Warning in mean.default(example_df$vec_char): 参数不是数值也不是逻辑值：回覆NA

    ## [1] NA

``` r
mean(example_df$vec_factor)
```

    ## Warning in mean.default(example_df$vec_factor): 参数不是数值也不是逻辑值：回覆NA

    ## [1] NA

``` r
as.numeric(example_df$rs)
```

    ##  [1]  1.0087536  0.9580910 -0.5226447  0.4448903 -1.0729106  0.5435970
    ##  [7] -0.9045458  0.3216994 -0.3312081 -0.0592730

``` r
as.numeric(example_df$vec_logical)
```

    ##  [1] 1 0 0 0 0 0 0 0 0 0

``` r
as.numeric(example_df$vec_char)
```

    ## Warning: 强制改变过程中产生了NA

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(example_df$vec_factor)
```

    ##  [1] 1 2 2 2 2 2 2 2 2 3

For mean, random sample and logical vector work, character vector and
factor vector don’t work. For convertion, only character vector does not
work.Because it is defined as character for system and could not be
ordered.
